server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:3306/aurora?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: username
    password: password

  redis:
    host: ip
    port: 6379
    password: password
    database: 0
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 100
        max-wait: 10000

  rabbitmq:
    host: ip
    port: 5672
    username: username
    password: password
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  elasticsearch:
    rest:
      uris: ip:9200

  mail:
    host: mail.host
    username: mail
    password: password
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secret: aurora

search:
  mode: elasticsearch

upload:
  mode: minio
  minio:
    url: http://ip:9000/
    endpoint: http://ip:9000
    accesskey: aurorauser
    secretKey: aurorauser
    bucketName: aurorapic

website:
  url: https://ip:port

justauth:
  enabled: true
  type:
    GITEE:
      client-id: client-id
      client-secret: client-secret
      redirect-uri: http://ip:port/users/oauth/callback/gitee
  cache:
    type: default
